const CACHE='kadr-shell-bootstrap-v2';
const SHELL=['/KADR/','/KADR/index.html','/KADR/config.js','/KADR/manifest.webmanifest','/KADR/icon-192.png','/KADR/icon-512.png','/KADR/apple-touch-icon.png','/KADR/platform-logos/cinema.svg'];
const BRAND_HOSTS=new Set(['cdn.jsdelivr.net','commons.wikimedia.org','upload.wikimedia.org','cdn.rcd.gg']);
async function warm(){const c=await caches.open(CACHE);await Promise.all(SHELL.map(async u=>{try{const r=await fetch(new Request(u,{cache:'reload'}));if(r.ok)await c.put(u,r.clone())}catch{}}))}
self.addEventListener('install',e=>e.waitUntil(warm().then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('kadr-shell-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin){if(BRAND_HOSTS.has(u.hostname)&&r.destination==='image')e.respondWith(caches.match(r).then(c=>c||fetch(r).then(res=>{if(res.ok||res.type==='opaque')caches.open(CACHE).then(x=>x.put(r,res.clone()));return res})));return}
  if(r.mode==='navigate'){e.respondWith(fetch(new Request(r,{cache:'no-store'})).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(r,res.clone()));return res}).catch(async()=>await caches.match(r)||await caches.match('/KADR/index.html')));return}
  const fresh=/\.(?:js|css|webmanifest|json|svg)$/i.test(u.pathname);if(fresh){e.respondWith(fetch(new Request(r,{cache:'no-store'})).then(res=>{if(res.ok)caches.open(CACHE).then(c=>c.put(r,res.clone()));return res}).catch(()=>caches.match(r)));return}
  e.respondWith(caches.match(r).then(c=>c||fetch(r).then(res=>{if(res.ok)caches.open(CACHE).then(x=>x.put(r,res.clone()));return res})));
});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();if(e.data?.type==='CLEAR_KADR_NOTIFICATIONS')e.waitUntil(self.registration.getNotifications().then(ns=>ns.forEach(n=>n.close())))});
const DEDUPE='kadr-push-dedupe-v2';
async function shouldShow(data){try{const tag=String(data.tag||`kadr-${data.kind||'notice'}-${data.version||''}`),c=await caches.open(DEDUPE),req=new Request(`${self.location.origin}/__kadr_push__/${encodeURIComponent(tag)}`),old=await c.match(req);if(old){const ts=Number(await old.text());if(Number.isFinite(ts)&&Date.now()-ts<15*60*1000)return false}await c.put(req,new Response(String(Date.now()),{headers:{'Cache-Control':'no-store'}}));return true}catch{return true}}
self.addEventListener('push',event=>event.waitUntil((async()=>{let data={};try{data=event.data?.json()||{}}catch{data={body:event.data?.text()||''}}if(!(await shouldShow(data)))return;const title=data.title||'كادر',tag=data.tag||`kadr-${data.kind||'notice'}-${data.version||''}`;try{(await self.registration.getNotifications({tag})).forEach(n=>n.close())}catch{}await self.registration.showNotification(title,{body:data.body||'لديك إشعار جديد',icon:'/KADR/icon-192.png',badge:'/KADR/icon-192.png',tag,renotify:false,data:{url:data.url||'/KADR/'}})})()));
function safeTarget(raw){try{const u=new URL(raw||'/KADR/',self.location.origin);if(u.origin===self.location.origin&&u.pathname.startsWith('/KADR/')){u.searchParams.delete('admin');u.searchParams.delete('dashboard');return u.href}return '/KADR/'}catch{return '/KADR/'}}
self.addEventListener('notificationclick',event=>{event.notification.close();const target=safeTarget(event.notification.data?.url);event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list)if('focus'in c){c.navigate(target);return c.focus()}return clients.openWindow(target)}))});
