const CACHE='kadr-shell-v1.10-r1';
const SHELL=['./','./index.html','./app.css','./app.js','./config.js','./manifest.webmanifest','/KADR/icon-192.png','/KADR/icon-512.png','/KADR/apple-touch-icon.png'];
async function cacheFresh(){const c=await caches.open(CACHE);await Promise.all(SHELL.map(async u=>{try{const r=await fetch(new Request(u,{cache:'reload'}));if(r.ok)await c.put(u,r.clone())}catch{}}))}
self.addEventListener('install',e=>{e.waitUntil(cacheFresh().then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k.startsWith('kadr-shell-')).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin)return;if(r.mode==='navigate'){e.respondWith(fetch(new Request(r,{cache:'no-store'})).then(res=>{const copy=res.clone();caches.open(CACHE).then(c=>c.put('./index.html',copy));return res}).catch(()=>caches.match('./index.html')));return}const freshAsset=/\.(?:js|css|webmanifest)$/i.test(u.pathname);if(freshAsset){e.respondWith(fetch(new Request(r,{cache:'no-store'})).then(res=>{if(res.ok){const copy=res.clone();caches.open(CACHE).then(c=>c.put(r,copy))}return res}).catch(()=>caches.match(r)));return}e.respondWith(caches.match(r).then(cached=>cached||fetch(r).then(res=>{if(res.ok){const copy=res.clone();caches.open(CACHE).then(c=>c.put(r,copy))}return res})))});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();if(e.data?.type==='CLEAR_KADR_NOTIFICATIONS')e.waitUntil(self.registration.getNotifications().then(ns=>ns.forEach(n=>n.close())))});
const PUSH_DEDUPE_CACHE='kadr-push-dedupe-v1';
async function shouldShowPush(data){try{const tag=String(data.tag||`kadr-${data.kind||'notice'}-${data.version||''}`),key=encodeURIComponent(tag),c=await caches.open(PUSH_DEDUPE_CACHE),req=new Request(`${self.location.origin}/__kadr_push__/${key}`),old=await c.match(req);if(old){const ts=Number(await old.text());if(Number.isFinite(ts)&&Date.now()-ts<15*60*1000)return false}await c.put(req,new Response(String(Date.now()),{headers:{'Cache-Control':'no-store'}}));return true}catch{return true}}
self.addEventListener('push',event=>{event.waitUntil((async()=>{let data={};try{data=event.data?.json()||{}}catch{data={body:event.data?.text()||''}}if(!(await shouldShowPush(data)))return;const title=data.title||'كادر',tag=data.tag||`kadr-${data.kind||'notice'}-${data.version||''}`;try{const old=await self.registration.getNotifications({tag});old.forEach(n=>n.close())}catch{}const options={body:data.body||'لديك تحديث جديد',icon:'/KADR/icon-192.png',badge:'/KADR/icon-192.png',tag,renotify:false,data:{url:data.url||'./'}};await self.registration.showNotification(title,options)})())});
function safeKadrTarget(raw){try{const u=new URL(raw||'./',self.location.origin);if(u.origin===self.location.origin&&u.pathname.startsWith('/KADR/')){u.searchParams.delete('admin');u.searchParams.delete('dashboard');return u.href}return raw||'./'}catch{return './'}}
self.addEventListener('notificationclick',event=>{event.notification.close();const target=safeKadrTarget(event.notification.data?.url);event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const c of list){if('focus'in c){c.navigate(target);return c.focus()}}return clients.openWindow(target)}))});
